### ISSUE TITLE
auc_logits.json

### ISSUE THREAD

**Issue by wagaabderrahim** [andreabac3/study-transfer-learning-covid-19#1]
(covid_env) PS C:\Users\ADMIN\Downloads\study-transfer-learning-covid-19-master> python ./src/test.py train.model_type=mobilenet_v2  train.pl_trainer.max_epochs=2 data.subset_percentage=1.0
------------
with open(filename, "r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMIN\\Downloads\\study-transfer-learning-covid-19-master/auroc_plot/auc_logits.json'

**Comment by andreabac3** [comment]
Hi @wagaabderrahim,

as the error suggest it tells you that the folder auroc_plot does not exist in your working directory. 
So you can do two things (a) create it; (b) comment out the line 
```python3
with open(filename, "r") as reader:
     json.load(reader)
```

Kind regards,
Andrea
